git clone https://android.googlesource.com/Kernel-Projects
git clone https://android.googlesource.com/Platform-Projects
git clone https://android.googlesource.com/Platform-Unrestricted-Projects
git clone https://android.googlesource.com/Public-Projects
git clone https://android.googlesource.com/accessories/manifest
git clone https://android.googlesource.com/device/asus/grouper
git clone https://android.googlesource.com/device/common
git clone https://android.googlesource.com/device/generic/armv7-a
git clone https://android.googlesource.com/device/generic/armv7-a-neon
git clone https://android.googlesource.com/device/generic/goldfish
git clone https://android.googlesource.com/device/google/accessory/adk2012
git clone https://android.googlesource.com/device/google/accessory/adk2012_demo
git clone https://android.googlesource.com/device/google/accessory/arduino
git clone https://android.googlesource.com/device/google/accessory/demokit
git clone https://android.googlesource.com/device/google/phantasm
git clone https://android.googlesource.com/device/htc/common
git clone https://android.googlesource.com/device/htc/dream
git clone https://android.googlesource.com/device/htc/dream-sapphire
git clone https://android.googlesource.com/device/htc/passion
git clone https://android.googlesource.com/device/htc/passion-common
git clone https://android.googlesource.com/device/htc/sapphire
git clone https://android.googlesource.com/device/moto/common
git clone https://android.googlesource.com/device/moto/stingray
git clone https://android.googlesource.com/device/moto/wingray
git clone https://android.googlesource.com/device/sample
git clone https://android.googlesource.com/device/samsung/crespo
git clone https://android.googlesource.com/device/samsung/crespo4g
git clone https://android.googlesource.com/device/samsung/maguro
git clone https://android.googlesource.com/device/samsung/toro
git clone https://android.googlesource.com/device/samsung/toroplus
git clone https://android.googlesource.com/device/samsung/torospr
git clone https://android.googlesource.com/device/samsung/tuna
git clone https://android.googlesource.com/device/sony/lt26
git clone https://android.googlesource.com/device/ti/bootloader/uboot
git clone https://android.googlesource.com/device/ti/panda
git clone https://android.googlesource.com/kernel/common
git clone https://android.googlesource.com/kernel/exynos
git clone https://android.googlesource.com/kernel/goldfish
git clone https://android.googlesource.com/kernel/msm
git clone https://android.googlesource.com/kernel/omap
git clone https://android.googlesource.com/kernel/samsung
git clone https://android.googlesource.com/kernel/tegra
git clone https://android.googlesource.com/mirror/manifest
git clone https://android.googlesource.com/platform/abi/cpp
git clone https://android.googlesource.com/platform/bionic
git clone https://android.googlesource.com/platform/bootable/bootloader/legacy
git clone https://android.googlesource.com/platform/bootable/diskinstaller
git clone https://android.googlesource.com/platform/bootable/recovery
git clone https://android.googlesource.com/platform/build
git clone https://android.googlesource.com/platform/cts
git clone https://android.googlesource.com/platform/dalvik
git clone https://android.googlesource.com/platform/dalvik-snapshot
git clone https://android.googlesource.com/platform/dalvik2
git clone https://android.googlesource.com/platform/development
git clone https://android.googlesource.com/platform/docs/source.android.com
git clone https://android.googlesource.com/platform/external/aac
git clone https://android.googlesource.com/platform/external/aes
git clone https://android.googlesource.com/platform/external/android-clat
git clone https://android.googlesource.com/platform/external/android-mock
git clone https://android.googlesource.com/platform/external/ant-glob
git clone https://android.googlesource.com/platform/external/antlr
git clone https://android.googlesource.com/platform/external/apache-apr
git clone https://android.googlesource.com/platform/external/apache-apr-util
git clone https://android.googlesource.com/platform/external/apache-harmony
git clone https://android.googlesource.com/platform/external/apache-http
git clone https://android.googlesource.com/platform/external/apache-log4cxx
git clone https://android.googlesource.com/platform/external/apache-qp
git clone https://android.googlesource.com/platform/external/apache-xml
git clone https://android.googlesource.com/platform/external/apple-coreaudiosamples
git clone https://android.googlesource.com/platform/external/arduino
git clone https://android.googlesource.com/platform/external/arduino-ide
git clone https://android.googlesource.com/platform/external/astl
git clone https://android.googlesource.com/platform/external/bison
git clone https://android.googlesource.com/platform/external/blktrace
git clone https://android.googlesource.com/platform/external/bluetooth/bluez
git clone https://android.googlesource.com/platform/external/bluetooth/glib
git clone https://android.googlesource.com/platform/external/bluetooth/hcidump
git clone https://android.googlesource.com/platform/external/bluez
git clone https://android.googlesource.com/platform/external/boost
git clone https://android.googlesource.com/platform/external/bouncycastle
git clone https://android.googlesource.com/platform/external/bsdiff
git clone https://android.googlesource.com/platform/external/bzip2
git clone https://android.googlesource.com/platform/external/checkpolicy
git clone https://android.googlesource.com/platform/external/chromium
git clone https://android.googlesource.com/platform/external/chromium-trace
git clone https://android.googlesource.com/platform/external/cibu-fonts
git clone https://android.googlesource.com/platform/external/clang
git clone https://android.googlesource.com/platform/external/clearsilver
git clone https://android.googlesource.com/platform/external/codesourcery
git clone https://android.googlesource.com/platform/external/collada
git clone https://android.googlesource.com/platform/external/compiler-rt
git clone https://android.googlesource.com/platform/external/curl
git clone https://android.googlesource.com/platform/external/dbus
git clone https://android.googlesource.com/platform/external/dexmaker
git clone https://android.googlesource.com/platform/external/dhcpcd
git clone https://android.googlesource.com/platform/external/dnsmasq
git clone https://android.googlesource.com/platform/external/doclava
git clone https://android.googlesource.com/platform/external/dosfstools
git clone https://android.googlesource.com/platform/external/dropbear
git clone https://android.googlesource.com/platform/external/e2fsprogs
git clone https://android.googlesource.com/platform/external/easymock
git clone https://android.googlesource.com/platform/external/eclipse-basebuilder
git clone https://android.googlesource.com/platform/external/eclipse-windowbuilder
git clone https://android.googlesource.com/platform/external/eglib
git clone https://android.googlesource.com/platform/external/elfcopy
git clone https://android.googlesource.com/platform/external/elfutils
git clone https://android.googlesource.com/platform/external/embunit
git clone https://android.googlesource.com/platform/external/emma
git clone https://android.googlesource.com/platform/external/esd
git clone https://android.googlesource.com/platform/external/expat
git clone https://android.googlesource.com/platform/external/eyes-free
git clone https://android.googlesource.com/platform/external/faad
git clone https://android.googlesource.com/platform/external/fat32lib
git clone https://android.googlesource.com/platform/external/fdlibm
git clone https://android.googlesource.com/platform/external/flac
git clone https://android.googlesource.com/platform/external/free-image
git clone https://android.googlesource.com/platform/external/freetype
git clone https://android.googlesource.com/platform/external/fsck_msdos
git clone https://android.googlesource.com/platform/external/ganymed-ssh2
git clone https://android.googlesource.com/platform/external/gcc-demangle
git clone https://android.googlesource.com/platform/external/gdata
git clone https://android.googlesource.com/platform/external/genext2fs
git clone https://android.googlesource.com/platform/external/giflib
git clone https://android.googlesource.com/platform/external/google-diff-match-patch
git clone https://android.googlesource.com/platform/external/googleclient
git clone https://android.googlesource.com/platform/external/grub
git clone https://android.googlesource.com/platform/external/gsoap
git clone https://android.googlesource.com/platform/external/gtest
git clone https://android.googlesource.com/platform/external/guava
git clone https://android.googlesource.com/platform/external/hamcrest
git clone https://android.googlesource.com/platform/external/harfbuzz
git clone https://android.googlesource.com/platform/external/harfbuzz_ng
git clone https://android.googlesource.com/platform/external/hcidump
git clone https://android.googlesource.com/platform/external/hsqldb
git clone https://android.googlesource.com/platform/external/hyphenation
git clone https://android.googlesource.com/platform/external/icu4c
git clone https://android.googlesource.com/platform/external/id3lib
git clone https://android.googlesource.com/platform/external/iproute2
git clone https://android.googlesource.com/platform/external/ipsec-tools
git clone https://android.googlesource.com/platform/external/iptables
git clone https://android.googlesource.com/platform/external/jack
git clone https://android.googlesource.com/platform/external/javasqlite
git clone https://android.googlesource.com/platform/external/javassist
git clone https://android.googlesource.com/platform/external/jdiff
git clone https://android.googlesource.com/platform/external/jenkins-hash
git clone https://android.googlesource.com/platform/external/jhead
git clone https://android.googlesource.com/platform/external/jline
git clone https://android.googlesource.com/platform/external/jmdns
git clone https://android.googlesource.com/platform/external/jmonkeyengine
git clone https://android.googlesource.com/platform/external/jpeg
git clone https://android.googlesource.com/platform/external/jsilver
git clone https://android.googlesource.com/platform/external/jsoncpp
git clone https://android.googlesource.com/platform/external/jsr305
git clone https://android.googlesource.com/platform/external/junit
git clone https://android.googlesource.com/platform/external/kernel-headers
git clone https://android.googlesource.com/platform/external/lame
git clone https://android.googlesource.com/platform/external/lcc
git clone https://android.googlesource.com/platform/external/libcap-ng
git clone https://android.googlesource.com/platform/external/libffi
git clone https://android.googlesource.com/platform/external/libgsm
git clone https://android.googlesource.com/platform/external/liblzf
git clone https://android.googlesource.com/platform/external/libmtp
git clone https://android.googlesource.com/platform/external/libnfc-nxp
git clone https://android.googlesource.com/platform/external/libnl-headers
git clone https://android.googlesource.com/platform/external/libogg
git clone https://android.googlesource.com/platform/external/libpcap
git clone https://android.googlesource.com/platform/external/libphonenumber
git clone https://android.googlesource.com/platform/external/libpng
git clone https://android.googlesource.com/platform/external/libselinux
git clone https://android.googlesource.com/platform/external/libsepol
git clone https://android.googlesource.com/platform/external/libusb
git clone https://android.googlesource.com/platform/external/libusb-compat
git clone https://android.googlesource.com/platform/external/libvorbis
git clone https://android.googlesource.com/platform/external/libvpx
git clone https://android.googlesource.com/platform/external/libxml2
git clone https://android.googlesource.com/platform/external/libxslt
git clone https://android.googlesource.com/platform/external/libyuv
git clone https://android.googlesource.com/platform/external/linux-tools-perf
git clone https://android.googlesource.com/platform/external/littlemock
git clone https://android.googlesource.com/platform/external/llvm
git clone https://android.googlesource.com/platform/external/login-items-ae
git clone https://android.googlesource.com/platform/external/lohit-fonts
git clone https://android.googlesource.com/platform/external/markdown
git clone https://android.googlesource.com/platform/external/mdnsresponder
git clone https://android.googlesource.com/platform/external/mesa3d
git clone https://android.googlesource.com/platform/external/mksh
git clone https://android.googlesource.com/platform/external/mockwebserver
git clone https://android.googlesource.com/platform/external/mp4v2
git clone https://android.googlesource.com/platform/external/mpg123
git clone https://android.googlesource.com/platform/external/mtpd
git clone https://android.googlesource.com/platform/external/naver-fonts
git clone https://android.googlesource.com/platform/external/netcat
git clone https://android.googlesource.com/platform/external/netperf
git clone https://android.googlesource.com/platform/external/neven
git clone https://android.googlesource.com/platform/external/nist-sip
git clone https://android.googlesource.com/platform/external/oauth
git clone https://android.googlesource.com/platform/external/okhttp
git clone https://android.googlesource.com/platform/external/opencore
git clone https://android.googlesource.com/platform/external/opencv
git clone https://android.googlesource.com/platform/external/openfst
git clone https://android.googlesource.com/platform/external/openssh
git clone https://android.googlesource.com/platform/external/openssl
git clone https://android.googlesource.com/platform/external/openvpn
git clone https://android.googlesource.com/platform/external/oprofile
git clone https://android.googlesource.com/platform/external/pcre
git clone https://android.googlesource.com/platform/external/ping
git clone https://android.googlesource.com/platform/external/ping6
git clone https://android.googlesource.com/platform/external/ppp
git clone https://android.googlesource.com/platform/external/proguard
git clone https://android.googlesource.com/platform/external/protobuf
git clone https://android.googlesource.com/platform/external/pthreads
git clone https://android.googlesource.com/platform/external/qemu
git clone https://android.googlesource.com/platform/external/qemu-pc-bios
git clone https://android.googlesource.com/platform/external/qt
git clone https://android.googlesource.com/platform/external/quake
git clone https://android.googlesource.com/platform/external/regex-re2
git clone https://android.googlesource.com/platform/external/replicaisland
git clone https://android.googlesource.com/platform/external/safe-iop
git clone https://android.googlesource.com/platform/external/sepolicy
git clone https://android.googlesource.com/platform/external/skia
git clone https://android.googlesource.com/platform/external/smali
git clone https://android.googlesource.com/platform/external/sonivox
git clone https://android.googlesource.com/platform/external/speex
git clone https://android.googlesource.com/platform/external/sqlite
git clone https://android.googlesource.com/platform/external/srec
git clone https://android.googlesource.com/platform/external/srtp
git clone https://android.googlesource.com/platform/external/stlport
git clone https://android.googlesource.com/platform/external/strace
git clone https://android.googlesource.com/platform/external/stressapptest
git clone https://android.googlesource.com/platform/external/svox
git clone https://android.googlesource.com/platform/external/tagsoup
git clone https://android.googlesource.com/platform/external/tcpdump
git clone https://android.googlesource.com/platform/external/tesseract
git clone https://android.googlesource.com/platform/external/tinyalsa
git clone https://android.googlesource.com/platform/external/tinyxml
git clone https://android.googlesource.com/platform/external/tremolo
git clone https://android.googlesource.com/platform/external/tremor
git clone https://android.googlesource.com/platform/external/unicode
git clone https://android.googlesource.com/platform/external/utf8proc
git clone https://android.googlesource.com/platform/external/v8
git clone https://android.googlesource.com/platform/external/valgrind
git clone https://android.googlesource.com/platform/external/webkit
git clone https://android.googlesource.com/platform/external/webp
git clone https://android.googlesource.com/platform/external/webrtc
git clone https://android.googlesource.com/platform/external/wpa_supplicant
git clone https://android.googlesource.com/platform/external/wpa_supplicant_6
git clone https://android.googlesource.com/platform/external/wpa_supplicant_8
git clone https://android.googlesource.com/platform/external/xdelta3
git clone https://android.googlesource.com/platform/external/xerces-cpp
git clone https://android.googlesource.com/platform/external/xmlwriter
git clone https://android.googlesource.com/platform/external/yaffs2
git clone https://android.googlesource.com/platform/external/zlib
git clone https://android.googlesource.com/platform/external/zxing
git clone https://android.googlesource.com/platform/frameworks/av
git clone https://android.googlesource.com/platform/frameworks/base
git clone https://android.googlesource.com/platform/frameworks/compile/libbcc
git clone https://android.googlesource.com/platform/frameworks/compile/linkloader
git clone https://android.googlesource.com/platform/frameworks/compile/mclinker
git clone https://android.googlesource.com/platform/frameworks/compile/slang
git clone https://android.googlesource.com/platform/frameworks/ex
git clone https://android.googlesource.com/platform/frameworks/media/libvideoeditor
git clone https://android.googlesource.com/platform/frameworks/mff
git clone https://android.googlesource.com/platform/frameworks/ml
git clone https://android.googlesource.com/platform/frameworks/native
git clone https://android.googlesource.com/platform/frameworks/opt/calendar
git clone https://android.googlesource.com/platform/frameworks/opt/carddav
git clone https://android.googlesource.com/platform/frameworks/opt/com.google.android
git clone https://android.googlesource.com/platform/frameworks/opt/com.google.android.googlelogin
git clone https://android.googlesource.com/platform/frameworks/opt/emoji
git clone https://android.googlesource.com/platform/frameworks/opt/inputmethodcommon
git clone https://android.googlesource.com/platform/frameworks/opt/mailcommon
git clone https://android.googlesource.com/platform/frameworks/opt/mms
git clone https://android.googlesource.com/platform/frameworks/opt/telephony
git clone https://android.googlesource.com/platform/frameworks/opt/vcard
git clone https://android.googlesource.com/platform/frameworks/policies/base
git clone https://android.googlesource.com/platform/frameworks/rs
git clone https://android.googlesource.com/platform/frameworks/support
git clone https://android.googlesource.com/platform/frameworks/testing
git clone https://android.googlesource.com/platform/frameworks/wilhelm
git clone https://android.googlesource.com/platform/gdk
git clone https://android.googlesource.com/platform/hardware/akm
git clone https://android.googlesource.com/platform/hardware/broadcom/wlan
git clone https://android.googlesource.com/platform/hardware/invensense
git clone https://android.googlesource.com/platform/hardware/libhardware
git clone https://android.googlesource.com/platform/hardware/libhardware_legacy
git clone https://android.googlesource.com/platform/hardware/msm7k
git clone https://android.googlesource.com/platform/hardware/qcom/gps
git clone https://android.googlesource.com/platform/hardware/qcom/media
git clone https://android.googlesource.com/platform/hardware/ril
git clone https://android.googlesource.com/platform/hardware/ti/omap3
git clone https://android.googlesource.com/platform/hardware/ti/omap4xxx
git clone https://android.googlesource.com/platform/hardware/ti/wlan
git clone https://android.googlesource.com/platform/hardware/ti/wpan
git clone https://android.googlesource.com/platform/libcore
git clone https://android.googlesource.com/platform/libcore-snapshot
git clone https://android.googlesource.com/platform/libcore2
git clone https://android.googlesource.com/platform/libnativehelper
git clone https://android.googlesource.com/platform/manifest
git clone https://android.googlesource.com/platform/motodev
git clone https://android.googlesource.com/platform/ndk
git clone https://android.googlesource.com/platform/packages/apps/AccountsAndSyncSettings
git clone https://android.googlesource.com/platform/packages/apps/AlarmClock
git clone https://android.googlesource.com/platform/packages/apps/BasicSmsReceiver
git clone https://android.googlesource.com/platform/packages/apps/Bluetooth
git clone https://android.googlesource.com/platform/packages/apps/Browser
git clone https://android.googlesource.com/platform/packages/apps/Calculator
git clone https://android.googlesource.com/platform/packages/apps/Calendar
git clone https://android.googlesource.com/platform/packages/apps/Camera
git clone https://android.googlesource.com/platform/packages/apps/CellBroadcastReceiver
git clone https://android.googlesource.com/platform/packages/apps/CertInstaller
git clone https://android.googlesource.com/platform/packages/apps/Contacts
git clone https://android.googlesource.com/platform/packages/apps/DeskClock
git clone https://android.googlesource.com/platform/packages/apps/Email
git clone https://android.googlesource.com/platform/packages/apps/Exchange
git clone https://android.googlesource.com/platform/packages/apps/Gallery
git clone https://android.googlesource.com/platform/packages/apps/Gallery2
git clone https://android.googlesource.com/platform/packages/apps/Gallery3D
git clone https://android.googlesource.com/platform/packages/apps/GlobalSearch
git clone https://android.googlesource.com/platform/packages/apps/GoogleSearch
git clone https://android.googlesource.com/platform/packages/apps/HTMLViewer
git clone https://android.googlesource.com/platform/packages/apps/IM
git clone https://android.googlesource.com/platform/packages/apps/KeyChain
git clone https://android.googlesource.com/platform/packages/apps/Launcher
git clone https://android.googlesource.com/platform/packages/apps/Launcher2
git clone https://android.googlesource.com/platform/packages/apps/LegacyCamera
git clone https://android.googlesource.com/platform/packages/apps/Mms
git clone https://android.googlesource.com/platform/packages/apps/Music
git clone https://android.googlesource.com/platform/packages/apps/MusicFX
git clone https://android.googlesource.com/platform/packages/apps/Nfc
git clone https://android.googlesource.com/platform/packages/apps/PackageInstaller
git clone https://android.googlesource.com/platform/packages/apps/Phone
git clone https://android.googlesource.com/platform/packages/apps/Protips
git clone https://android.googlesource.com/platform/packages/apps/Provision
git clone https://android.googlesource.com/platform/packages/apps/QuickSearchBox
git clone https://android.googlesource.com/platform/packages/apps/Settings
git clone https://android.googlesource.com/platform/packages/apps/SmartCardService
git clone https://android.googlesource.com/platform/packages/apps/SoundRecorder
git clone https://android.googlesource.com/platform/packages/apps/SpareParts
git clone https://android.googlesource.com/platform/packages/apps/SpeechRecorder
git clone https://android.googlesource.com/platform/packages/apps/Stk
git clone https://android.googlesource.com/platform/packages/apps/Sync
git clone https://android.googlesource.com/platform/packages/apps/Tag
git clone https://android.googlesource.com/platform/packages/apps/Updater
git clone https://android.googlesource.com/platform/packages/apps/VideoEditor
git clone https://android.googlesource.com/platform/packages/apps/VoiceDialer
git clone https://android.googlesource.com/platform/packages/experimental
git clone https://android.googlesource.com/platform/packages/inputmethods/LatinIME
git clone https://android.googlesource.com/platform/packages/inputmethods/OpenWnn
git clone https://android.googlesource.com/platform/packages/inputmethods/PinyinIME
git clone https://android.googlesource.com/platform/packages/providers/ApplicationsProvider
git clone https://android.googlesource.com/platform/packages/providers/CalendarProvider
git clone https://android.googlesource.com/platform/packages/providers/ContactsProvider
git clone https://android.googlesource.com/platform/packages/providers/DownloadProvider
git clone https://android.googlesource.com/platform/packages/providers/DrmProvider
git clone https://android.googlesource.com/platform/packages/providers/GoogleContactsProvider
git clone https://android.googlesource.com/platform/packages/providers/GoogleSubscribedFeedsProvider
git clone https://android.googlesource.com/platform/packages/providers/ImProvider
git clone https://android.googlesource.com/platform/packages/providers/ManagementProvider
git clone https://android.googlesource.com/platform/packages/providers/MediaProvider
git clone https://android.googlesource.com/platform/packages/providers/PartnerBookmarksProvider
git clone https://android.googlesource.com/platform/packages/providers/TelephonyProvider
git clone https://android.googlesource.com/platform/packages/providers/UserDictionaryProvider
git clone https://android.googlesource.com/platform/packages/providers/WebSearchProvider
git clone https://android.googlesource.com/platform/packages/services/EasService
git clone https://android.googlesource.com/platform/packages/services/LockAndWipe
git clone https://android.googlesource.com/platform/packages/wallpapers/Basic
git clone https://android.googlesource.com/platform/packages/wallpapers/Galaxy4
git clone https://android.googlesource.com/platform/packages/wallpapers/HoloSpiral
git clone https://android.googlesource.com/platform/packages/wallpapers/LivePicker
git clone https://android.googlesource.com/platform/packages/wallpapers/MagicSmoke
git clone https://android.googlesource.com/platform/packages/wallpapers/MusicVisualization
git clone https://android.googlesource.com/platform/packages/wallpapers/NoiseField
git clone https://android.googlesource.com/platform/packages/wallpapers/PhaseBeam
git clone https://android.googlesource.com/platform/pdk
git clone https://android.googlesource.com/platform/prebuilt
git clone https://android.googlesource.com/platform/prebuilts/eclipse
git clone https://android.googlesource.com/platform/prebuilts/eclipse-build-deps
git clone https://android.googlesource.com/platform/prebuilts/eclipse-build-deps-sources
git clone https://android.googlesource.com/platform/prebuilts/gcc/darwin-x86/arm/arm-eabi-4.6
git clone https://android.googlesource.com/platform/prebuilts/gcc/darwin-x86/arm/arm-eabi-4.7
git clone https://android.googlesource.com/platform/prebuilts/gcc/darwin-x86/arm/arm-linux-androideabi-4.6
git clone https://android.googlesource.com/platform/prebuilts/gcc/darwin-x86/arm/arm-linux-androideabi-4.7
git clone https://android.googlesource.com/platform/prebuilts/gcc/darwin-x86/mips/mipsel-linux-android-4.4.3
git clone https://android.googlesource.com/platform/prebuilts/gcc/darwin-x86/mips/mipsel-linux-android-4.6
git clone https://android.googlesource.com/platform/prebuilts/gcc/darwin-x86/mips/mipsel-linux-android-4.7
git clone https://android.googlesource.com/platform/prebuilts/gcc/darwin-x86/x86/i686-android-linux-4.4.3
git clone https://android.googlesource.com/platform/prebuilts/gcc/darwin-x86/x86/i686-android-linux-4.6
git clone https://android.googlesource.com/platform/prebuilts/gcc/darwin-x86/x86/i686-linux-android-4.6
git clone https://android.googlesource.com/platform/prebuilts/gcc/darwin-x86/x86/i686-linux-android-4.7
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.6
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.7
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.6
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.7
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/host/i686-linux-glibc2.7-4.4.3
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/host/i686-linux-glibc2.7-4.6
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.7-4.6
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/mips/mipsel-linux-android-4.4.3
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/mips/mipsel-linux-android-4.6
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/mips/mipsel-linux-android-4.7
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/x86/i686-android-linux-4.4.3
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/x86/i686-android-linux-4.6
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/x86/i686-linux-android-4.6
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/x86/i686-linux-android-4.7
git clone https://android.googlesource.com/platform/prebuilts/misc
git clone https://android.googlesource.com/platform/prebuilts/ndk
git clone https://android.googlesource.com/platform/prebuilts/qemu-kernel
git clone https://android.googlesource.com/platform/prebuilts/sdk
git clone https://android.googlesource.com/platform/prebuilts/tools
git clone https://android.googlesource.com/platform/sdk
git clone https://android.googlesource.com/platform/system/bluetooth
git clone https://android.googlesource.com/platform/system/core
git clone https://android.googlesource.com/platform/system/extras
git clone https://android.googlesource.com/platform/system/media
git clone https://android.googlesource.com/platform/system/netd
git clone https://android.googlesource.com/platform/system/security
git clone https://android.googlesource.com/platform/system/vold
git clone https://android.googlesource.com/platform/system/wlan/ti
git clone https://android.googlesource.com/platform/tools/build
git clone https://android.googlesource.com/platform/tools/motodev
git clone https://android.googlesource.com/platform/tools/tradefederation
git clone https://android.googlesource.com/platform/vendor/htc/dream-open
git clone https://android.googlesource.com/platform/vendor/sample
git clone https://android.googlesource.com/toolchain/avr-libc
git clone https://android.googlesource.com/toolchain/benchmark
git clone https://android.googlesource.com/toolchain/binutils
git clone https://android.googlesource.com/toolchain/build
git clone https://android.googlesource.com/toolchain/ccache
git clone https://android.googlesource.com/toolchain/clang
git clone https://android.googlesource.com/toolchain/expat
git clone https://android.googlesource.com/toolchain/gcc
git clone https://android.googlesource.com/toolchain/gdb
git clone https://android.googlesource.com/toolchain/gmp
git clone https://android.googlesource.com/toolchain/gold
git clone https://android.googlesource.com/toolchain/llvm
git clone https://android.googlesource.com/toolchain/manifest
git clone https://android.googlesource.com/toolchain/mpc
git clone https://android.googlesource.com/toolchain/mpfr
git clone https://android.googlesource.com/tools/repo
